### PR TITLE
fix column_type for non-enum user defined types

### PR DESCRIPTION
**Pull request by makslevental**
fix https://github.com/vattle/sqlboiler/issues/131

### CODE REVIEW

**Comment by aarondl** [comment]
What version of postgres is this? I expect that the column type to read as USER-DEFINED. I'm a bit curious why it's null here.

**Comment by makslevental** [comment]
@aarondl `PostgreSQL 9.6.2 on x86_64-pc-linux-gnu, compiled by gcc (Debian 4.9.2-10) 4.9.2, 64-bit`

i can write a docker script that'll demonstrate if you want

**Comment by aarondl** [comment]
That's not necessary. I'll take a look at this soon. Thanks for the PR :)

**Comment by makslevental** [comment]
@aarondl I don't know if this is a great solution to the problem. what I'd really like is the ability to specify a module with "custom types" like knq/xo allows but that'll require some work.

**Comment by aarondl** [comment]
@makslevental We have a solution for this actually. It's just not built. We're going to pull the drivers out of sqlboiler and make them separate binaries that speak JSON. Then you can have any types you want.

**Comment by aarondl** [comment]
See resolution here: https://github.com/vattle/sqlboiler/issues/131

**Pull request closed without merging**
